### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by victorleal** [binarygenius/phpthewrongway#12]
I've just read your text and I agree with some things in there.

But, I have to talk about frameworks.

You said at the FAQ section:

> Q: If a framework can get me up and running quickly, why is that so bad?
> 
> If you have analyzed the situation and long term implications and you then see that “getting up and running quickly” is the only problem you ever have to deal with, then it’s not bad, but then we’re hardly dealing with programming or software development, we’re dealing mostly with point-n-click solutions.
> 
> Getting up and running quickly isn’t designing software, it mostly means you haven’t analyzed the problem you’re facing and you haven’t understood the long term implications of your choice. 

I'm using a framework to build an administrative application. At the end of the day, we really use a framework to get up quickly (we can put question on this point, because we have the framework learning curve) and this does not mean that we didn't analyze the problem at all. We want all of those frameworks helpers to focus on the main problem (Yes, this is the frameworks' mantra).

I agree with you that, when using a framework, we have to follow the framework's architecture, which is not good at all. But using a framework is not that bad.  Sometimes we don't have a team to build up things from the scratch and we have to think about a lot of details that a framework can handle for us.

This is just a comment. I've lived both sides of the coin and now, given the application size that I'm developing, I would prefer to use a framework

**Comment by lianglee** [comment]
Using a framework for new programmers is always bad idea,  just learn how to program and develop your own framework that even help you to make your developer more faster then using someone framework.

Well i just say the framework owner is the one who can understand its use then others.

**Comment by bitflop** [comment]
> I agree with you that, when using a framework, we have to follow the framework's architecture, which is not good at all. But using a framework is not that bad. Sometimes we don't have a team to build up things from the scratch and we have to think about a lot of details that a framework can handle for us.

What you're saying is a bit self-contradictory IMHO in that something being "not good at all" at the same time is "not that bad". But I do understand your point. Sometimes you don't have a choice maybe due to the clients financial restrictions or time constraints etc.

The problem with the situation you're facing is a good example of a very "dangerous" situation, especially for your client, but also for your reputation as a professional programmer because the client will eventually blame you.

If you have analyzed the situation and long term implications and you're absolutely sure that using the framework isn't going to cause any problems, then there's nothing wrong with that.

However, every time something like this goes wrong, it's always, without exception, the result of a lack of predictability about future requirements and needs. And when you have to start over from scratch, and the client feels he/her wasted a lot of money for the "first edition" that's when it gets really ugly.

If however you put your application together using libraries, you will never face the same kind of problem.

**Comment by agauniyal** [comment]
The one thing consistent with php ecosystem is - everyone wants to impose certain set of rules/views over others. There are lots of good points on the website, but when you make them sound with the attitude "I'm always right", then you're doing no good.

Frameworks are definitely not a good way to start out with php due to increase in abstractions, but that's probably because of how they're written. Other languages and their ecosystem don't suffer this problem. And neither is using a framework a crime. Using a framework for every other task which you could've written in < 100 lines of php isn't a crime either, it's either laziness or a bit of stupidity. Again, it depends on the context. Need to spin up a website which a client is demanding to get completed in 2days? You don't have to rewrite and reinvent all of the stuff from scratch, just use a library and/or drop a framework and complete the task. But that's not stupidity at all, the guy's probably bit smarter than you.

Framework also helps when you're working with a large team which might be making new inclusions at later stage. Because there's a high probability that the new guy could be already familiar with basic gist of it and now just has to work his way in and out of it. You might consider yourself to be a 10xer who can pickup any legacy application in a day or two, you should know that others aren't like you and there are time and costs attached with their training days too. Frameworks that get picked up by community do have a greater probablity that they might've been written by an experienced and good programmer, so that's another advantage that you're making good choices. Bugs are solved faster, features are introduced way sooner than you could've completed. Not to mention that you might've to learn and understand about a feature well, before introducing it.

> PHP on the other hand was created in the beginning by Rasmus Lerdorf as a set of tools written in C that would enable you to easily and quickly develop dynamic HTML. As such PHP was, and still is, a framework in and of itself.

You're probably trying to convey some sort of points but this doesn't even makes sense to me.

So @victorleal just take away good points from anywhere, evaluate them yourself and decide whether they fit into your way of doing things or not.

And @binarygenius if you aren't aware, you can serve a bunch of static pages without php, within github itself. Or unless you've other plans or are justifying the name of website.
