### ISSUE TITLE
Is a test suite needed for the project?

### ISSUE THREAD

**Issue by umutphp** [binarygenius/phpthewrongway#62]
Hi @unixsheikh,

Do you need a test suite to validate the created sites?

**Comment by unixdigest** [comment]
Hi @umutphp, what kind of tests/validations are you thinking of?

**Comment by umutphp** [comment]
I mean the validation of result html for every locale. 
For example;
* Checking the HTML with a linter
* Checking the list in navigation
* Checking if the H1 tags are correct 
etc

**Comment by unixdigest** [comment]
I do not think that we need this at the moment since the HTML is automatically produced by Pandoc from the Markdown documents and it produces valid HTML 5 (as far as I have noticed and tested). If for example the HTML produced by Pandoc isn't generated correctly and as a result isn't validated positively by the linter then it would maybe require some manual hacking to fix it (unless I have misunderstood your point).

On the other hand, when someone does a completely new translation, I currently have to manually check that every Markdown section is available, not missing anything, etc. Having this automated/tested during the "Make" procedure would be very nice.

**Comment by umutphp** [comment]
I am not to much familiar with the "Make" procedure but I will try to do it if it is ok for you :). 

I have two questions;

1. Is only a file by file check without checking the contents enough for you? 
2. If file in a locale does not exist, should the Make stop the creation of all locale or the problematic locale?
