### ISSUE TITLE
Did Rasmus Lerdorf change his opinion about frameworks? 

### ISSUE THREAD

**Issue by tirengarfio** [binarygenius/phpthewrongway#73]
Hi, 

you can find at this [video](https://www.youtube.com/watch?v=Hc4S74LCXHo) that Rasmus Lerdorf changed his mind about frameworks. He said something like "don't create your own framework" on 3:44.

There is a Rasmus' quote on this repository saying "All general purpose PHP frameworks suck!". Do you think that should be removed now?

**Comment by unixdigest** [comment]
That is a good question. Rasmus and his team was faced with a lot of problems with the in-house framework they made at Etsy, which is why he is now saying, "Don't create your own framework".

His current statement turns the subject into a debate about whether you should build your own framework or use a general purpose one, but it doesn't change the fact that all general purpose frameworks suck.

The reason why he originally made the statement that all general purpose frameworks suck was because very rarely does a general purpose framework suit a specific problem, and normally we're dealing with specific problems, not general problems.

His quote is not important, so we could just remove it.

**Comment by avidality** [comment]
but he did say it, the creator of PHP said that all PHP frameworks suck

**Comment by unixdigest** [comment]
We will just leave the quote as it is still correct in the context of when and why it was said.
